{
 "title": "Cantor",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostName",
    "label": "实例",
    "query": "SHOW TAG VALUES WITH KEY = \"hostName\""
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "description": "内存相关指标",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "HeapMemoryUsage_used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MemoryImpl",
     "select": [
      [
       { "params": [ "HeapMemoryUsage_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostName", "operator": "=~", "value": "/^$hostName$/" }
     ]
    },
    {
     "alias": "NonHeapMemoryUsage_used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "MemoryImpl",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostName", "operator": "=~", "value": "/^$hostName$/" }
     ]
    }
   ]
  },
  {
   "title": "CUP",
   "type": "graph",
   "description": "CPU指标",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "SystemCpuLoad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "OperatingSystemImpl",
     "select": [
      [
       { "params": [ "SystemCpuLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostName", "operator": "=~", "value": "/^$hostName$/" }
     ]
    },
    {
     "alias": "ProcessCpuLoad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "OperatingSystemImpl",
     "select": [
      [
       { "params": [ "ProcessCpuLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostName", "operator": "=~", "value": "/^$hostName$/" }
     ]
    }
   ]
  },
  {
   "title": "CollectionTime",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CollectionTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "GarbageCollectorImpl",
     "select": [
      [
       { "params": [ "CollectionTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostName", "operator": "=~", "value": "/^$hostName$/" }
     ]
    }
   ]
  },
  {
   "title": "CollectionCount",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "CollectionCount",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GarbageCollectorImpl",
     "select": [
      [
       { "params": [ "CollectionCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostName", "operator": "=~", "value": "/^$hostName$/" }
     ]
    }
   ]
  },
  {
   "title": "Threading",
   "type": "graph",
   "description": "线程相关指标",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ThreadCount",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "JvmThreadingImpl",
     "select": [
      [
       { "params": [ "ThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostName", "operator": "=~", "value": "/^$hostName$/" }
     ]
    },
    {
     "alias": "DaemonThreadCount",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "JvmThreadingImpl",
     "select": [
      [
       { "params": [ "DaemonThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostName", "operator": "=~", "value": "/^$hostName$/" }
     ]
    },
    {
     "alias": "PeakThreadCount",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "JvmThreadingImpl",
     "select": [
      [
       { "params": [ "PeakThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostName", "operator": "=~", "value": "/^$hostName$/" }
     ]
    },
    {
     "alias": "TotalStaredThreadCount",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "JvmThreadingImpl",
     "select": [
      [
       { "params": [ "TotalStartedThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostName", "operator": "=~", "value": "/^$hostName$/" }
     ]
    }
   ]
  }
 ]
}